### ISSUE TITLE
apt-cacher: use a vars section in inventory

### ISSUE THREAD

**Issue by el-blanco** [el-blanco/ansible-demos#2]
instead of 
```
clients:
  hosts:
    host0:
      apt_cacher_hostname: myapt-cache-server.example.com
      apt_cacher_port: 3142    
    host1:
      apt_cacher_hostname: myapt-cache-server.example.com
      apt_cacher_port: 3142    
```
do this
```
clients:
  vars:
    apt_cacher_server: myapt-cache-server.example.com
    apt_cacher_port: 3142
  hosts:
    host0:    
    host1:    
    wkstation0:    
    wkstation1:    
    desktop0:
```
since all clients/hosts need to be configured in the same way (except server, which uses localhost)
